### PR TITLE
Update : Tasks don't collide now

### PR DESCRIPTION
**Pull request by killerraj369**
hey,
Before the tasks were colliding each other and was distorting the project.
Fix the issue . Kindly Merge the PR

### CODE REVIEW

**Comment by chintan0513** [comment]
Please don't delete content from the .js file. Try to improve it.

**Comment by killerraj369** [comment]
@chintan0513 Sorry it occured due to the fact I commented out some of my features.
Issue have been perfectly resolved. Now you can my Merge the PR. I have also updated Delete Button

**Comment by chintan0513** [comment]
Thank you I checked it works well but can you please add a few margins or paddings between the button and task? Then I'll merge it.

**Comment by hrishikeshps** [comment]
Hey @killerraj369 
I have also created a PR with fixtures related to the delete button, added a margin, and styled the button. So, if @chintan0513 is okay with this, then we can contribute together?

**Comment by chintan0513** [comment]
Okay you can work on it,

**Comment by killerraj369** [comment]
Hey @chintan0513 You can merge this PR.
I wish to make A new PR for the issue #11. 
Close Issue #13.

**Comment by chintan0513** [comment]
Perfect, closing here #7

**Pull request merged**
