### PR TITLE
added delete all button

### PR DESCRIPTION
**Pull request by VIJAYKATARI23**
Hi,
Please review my pr for Hacktoberfest .
Solves Issue #18

### CODE REVIEW

**Comment by chintan0513** [comment]
Can you please move it to the input box, just right side of it.

**Comment by VIJAYKATARI23** [comment]
Yes sir I will do it tonight sir please give sometime as Im in class now

**Review by VIJAYKATARI23 — COMMENTED** [review]
Added delete all button to right of input box

**Comment by chintan0513** [comment]
Perfect, just update your repo and copy the CSS code from add button.

**Comment by VIJAYKATARI23** [comment]
Added CSS code for delete all button

**Comment by VIJAYKATARI23** [comment]
@chintan0513 I updated the repo and added css code also , please merge my repo.

**Comment by chintan0513** [comment]
Kindly update your current branch to the latest one.

**Pull request closed without merging**
