### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by hritikbhattacharya**
I have updated the style sheet . for the dark mode . Before the fix , the color of the text is not visible , and also the todo items are not appearing in vertical direction. All the described issues i have solved , so you review the changes

### CODE REVIEW

**Comment by chintan0513** [comment]
Thank you for your contribution please try to use small fonts. Then I'll add your PR and merge it.

**Comment by hritikbhattacharya** [comment]
i have chnged the font size now you check

**Comment by hritikbhattacharya** [comment]
i have done the changes

**Comment by chintan0513** [comment]
What about 1.5rem? If it is possible then could you please share the snapshot of it?

**Comment by hritikbhattacharya** [comment]
image
now chek

**Comment by chintan0513** [comment]
Perfect, thank you for your contribution👍🏻 closing here #19

**Comment by hritikbhattacharya** [comment]
is this contribution is considered in hactoberfest?

**Comment by chintan0513** [comment]
yes 
try to update your branch and later on try to make PR and solve the conflicts

**Comment by hritikbhattacharya** [comment]
you will not merge this branch?

**Comment by chintan0513** [comment]
This branch has still some conflicts please solve it.

**Pull request closed without merging**
