### PR TITLE
Fixing toggle dark mode button and Adding favicon

### PR DESCRIPTION
**Pull request by Dimas-Saputra-Me**
- [x] Fixing toggle dark mode button
- [x] Adding favicon

Let me know if I need to change or add something.

**\~Thank You\~**

### CODE REVIEW

**Comment by chintan0513** [comment]
Please add a 3D favicon illustrations and thank you for the contribution in other part.

**Comment by Dimas-Saputra-Me** [comment]
@chintan0513 I have changed the favicon, please let me know if I need to change it again to any specific 3d icons assets.

**\~Thank You\~**

**Comment by chintan0513** [comment]
Looks perfect just add this one and then I'll merge it

link: https://cdn3d.iconscout.com/3d/premium/thumb/checklist-3408629-2838148.png

**Comment by Dimas-Saputra-Me** [comment]
> Looks perfect just add this one and then I'll merge it
> 
> link: https://cdn3d.iconscout.com/3d/premium/thumb/checklist-3408629-2838148.png

@chintan0513 
Alright, I've changed the favicon to this 3d icon, let me know if I need to change or add something again.

**\~Thank You\~**

**Comment by chintan0513** [comment]
Perfect and Thank you for your contribution. 👍🏻 Closing here #8

**Pull request merged**
