### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by namit343**

### CODE REVIEW

**Comment by chintan0513** [comment]
Yes you can work on it.

**Comment by namit343** [comment]
Alright

**Comment by chintan0513** [comment]
Please add few content in it and then I'll surely merge your PR.

**Comment by namit343** [comment]
You have to provide me with some more details of the project.

**Comment by chintan0513** [comment]
Try to add steps for contribution as well as the title of it, project description, implementation steps

**Pull request closed without merging**
