### PR TITLE
Added html code for delete all button.

### PR DESCRIPTION
**Pull request by VIJAYKATARI23**
Please review my code for delete all button and please merge with#18 issue with Hacktoberfest tag.

### CODE REVIEW

**Comment by chintan0513** [comment]
The delete all button not working here. Please review it once.

**Comment by VIJAYKATARI23** [comment]
I edited code for both html and css files.

**Comment by VIJAYKATARI23** [comment]
Please check it now

**Comment by VIJAYKATARI23** [comment]
Please merge this issue

**Comment by VIJAYKATARI23** [comment]
Please merge my pr for hacktoberfest

**Pull request closed without merging**
